version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install Go 1.19
          command: |
              sudo rm -rf /usr/local/go
              wget -O go.tgz https://dl.google.com/go/go1.19.linux-amd64.tar.gz
              sudo tar -C /usr/local -xzf go.tgz
              which go
              go version
      - run:
          name: Run Download
          command: |
              go mod download
      - run:
          name: Run vet
          command: |
              go vet ./...
      - run:
          name: Run staticheck
          command: |
              wget -O staticcheck.tgz https://github.com/dominikh/go-tools/releases/download/v0.3.3/staticcheck_linux_amd64.tar.gz
              sudo tar -xzf staticcheck.tgz
              ./staticcheck/staticcheck --version
              ./staticcheck/staticcheck ./...
      - run:
          name: Run tests
          command: 
              go test -v ./...
